# safelist
branches:
  only:
    - master

language: node_js

services:
  - docker

before_install:
  - docker pull localstack/localstack

node_js:
  - stable

install:
  - npm install

script:
  - npm test
  - wget https://releases.hashicorp.com/terraform/0.12.13/terraform_0.12.13_linux_amd64.zip -O terraform.zip
  - unzip terraform.zip
  - export PATH=$PATH;`pwd`/terraform
  - devops/deployments/run.sh pro deploy

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"